#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

export FORCE_COLOR=1

pnpm run check:format ||
(
  echo '💀❌ Ooops! Prettier checking process has failed!';
  false;
)

pnpm run check:lint ||
(
  echo '💀❌ Ooops! Eslint checking process has failed!';
  false;
)

pnpm run check:spelling ||
(
  echo '💀❌ Ooops! Cspell checking process has failed!';
  false;
)

pnpm run check:types ||
(
  echo '💀❌ Ooops! Types checking process has failed!';
  false;
)

pnpm run test:coverage ||
(
  echo '💀❌ Ooops! Test has failed!';
  false;
)

echo '🥳✅ Successfully completed!'
